apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;
        proxy_cache_path    /var/cache/nginx keys_zone=image-cache:10m;
        include /etc/nginx/conf.d/*.conf;
    }
  app.nginx.config: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        
        server_tokens off;

        client_max_body_size 1G;

        proxy_intercept_errors on;
        error_page 404 /404.html;


        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api {
            proxy_pass http://backend:80;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /images/full {
            proxy_pass http://backend:80/images/;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /images/tiny {
            rewrite ^/images/tiny/(.*)$ /insecure/resize:fit:20:0:no:0/plain/http://backend:80/images/$1 break;

            proxy_pass http://imgproxy:80;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache             image-cache;
            proxy_cache_key         $uri$http_accept;
            proxy_cache_lock        on;
        }

        location /images {
            rewrite ^/images/(.*)$ /insecure/resize:fit:825:0:no:0/plain/http://backend:80/images/$1 break;

            proxy_pass http://imgproxy:80;
            proxy_set_header Host $host;
            proxy_set_header x-forwarded-for $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache             image-cache;
            proxy_cache_key         $uri$http_accept;
            proxy_cache_lock        on;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
